# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


adventure = Genre.create(name:"adventure")
action = Genre.create(name:"action")
adult = Genre.create(name:"adult")
comedy = Genre.create(name:"comedy")
cooking = Genre.create(name:"cooking")
doujinshi = Genre.create(name:"doujinshi")
drama = Genre.create(name:"drama")
ecchi = Genre.create(name:"ecchi")
fantasy = Genre.create(name:"fantasy")
gender_bender = Genre.create(name:"gender bender")
harem = Genre.create(name:"harem")
historical = Genre.create(name:"historical")
horror = Genre.create(name:"horror")
josei = Genre.create(name:"josei")
manhua = Genre.create(name:"manhua")
manhwa = Genre.create(name:"manhwa")
martial_arts = Genre.create(name:"martialarts")
mature	= Genre.create(name:"mature")
mecha	= Genre.create(name:"mecha")
medical= Genre.create(name:"medical")
mystery	= Genre.create(name:"mystery")
one_Shot	= Genre.create(name:"one shot")
psychological= Genre.create(name:"psychological")
romance	= Genre.create(name:"romance")
school_life	= Genre.create(name:"schoollife")
sci_fi= Genre.create(name:"scifi")
seinen	= Genre.create(name:"seinen")
shoujo	= Genre.create(name:"shoujo")
shoujo_ai= Genre.create(name:"shoujoai")
shounen	= Genre.create(name:"shounen")
shounen_ai	= Genre.create(name:"shounenai")
slice_of_life= Genre.create(name:"sliceoflife")
smut	= Genre.create(name:"smut")
sports	= Genre.create(name:"sports")
supernatural= Genre.create(name:"supernatural")
tragedy	= Genre.create(name:"tragedy")
webtoons	= Genre.create(name:"webtoons")
yaoi= Genre.create(name:"yaoi")
yuri= Genre.create(name:"yuri")